# Generated by Django 6.0 on 2026-03-20 09:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('calories_per_day', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eaten_on', models.DateField(default=django.utils.timezone.localdate)),
                ('name', models.CharField(max_length=120)),
                ('calories', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
