# Generated by Django 5.2.8 on 2025-11-29 15:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=12, max_digits=24, validators=[django.core.validators.MinValueValidator(1e-12)])),
                ('valid_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-valid_at'],
            },
        ),
        migrations.CreateModel(
            name='OwningSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(blank=True, choices=[('PERSON', 'Person'), ('GROUP', 'Group'), ('ORGANIZATION', 'Organization'), ('OTHER', 'Other')], max_length=16, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=8, help_text='Always positive. Direction is implied by type.', max_digits=20, validators=[django.core.validators.MinValueValidator(1e-08)])),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('category', models.CharField(choices=[('HOME_MAINTENANCE', 'Home & maintenance'), ('FOOD_GROCERIES', 'Food & groceries'), ('HOUSEHOLD_UTILITIES', 'Household & utilities'), ('CLOTHES_EDC', 'Clothes & EDC'), ('MOBILITY_TRANSPORT', 'Mobility & Transport'), ('FUN_TRAVEL', 'Fun & Travel'), ('LIFESTYLE_HOBBY', 'Lifestyle & Hobby'), ('WORK_EDUCATION', 'Work & Education'), ('BUSINESS_FINANCE', 'Business & Finance'), ('TAX_FEES', 'Tax & Fees'), ('GIFTS_FAMILY', 'Gifts & Family'), ('OTHER', 'Other')], max_length=32)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('symbol', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=64)),
                ('decimals', models.PositiveSmallIntegerField(help_text='Number of fractional digits used for this unit.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Europe/Warsaw', max_length=64)),
                ('locale', models.CharField(default='pl_PL', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='AssetSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('CASH_WALLET', 'Cash wallet'), ('BANK_ACCOUNT', 'Bank account'), ('PHYSICAL_ASSETPhysical Asset', 'Physical Asset'), ('INVESTMENT_ACCOUNTINVESTMENT_ACCOUNT', 'Investment Account'), ('CARD_ACCOUNT', 'Card Account'), ('LIABILITY_ACCOUNT', 'Liability Account'), ('CRYPTO_WALLET', 'Crypto Wallet'), ('OTHER', 'Other')], max_length=64)),
                ('external_id', models.CharField(blank=True, help_text='IBAN, last4, etc.', max_length=64, null=True)),
                ('active', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_sources', to='finances.owningsubject')),
            ],
            options={
                'ordering': ['subject__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='finances.owningsubject')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectUserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('EDITOR', 'Editor'), ('VIEWER', 'Viewer')], max_length=8)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='finances.owningsubject')),
            ],
        ),
    ]
