# Generated by Django 5.2.8 on 2025-11-29 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectuseraccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_asset_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='finances.assetsource'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finances.project'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finances.owningsubject'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_asset_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='finances.assetsource'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finances.unit'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='from_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates_from', to='finances.unit'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='to_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates_to', to='finances.unit'),
        ),
        migrations.AddField(
            model_name='assetsource',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_sources', to='finances.unit'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='default_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.unit'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('subject', 'name')},
        ),
        migrations.AddIndex(
            model_name='subjectuseraccess',
            index=models.Index(fields=['subject', 'role'], name='finances_su_subject_81ad6d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectuseraccess',
            unique_together={('user', 'subject')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['subject', 'occurred_at'], name='finances_tr_subject_56e587_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type'], name='finances_tr_type_db9430_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category'], name='finances_tr_categor_0d5e70_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['project'], name='finances_tr_project_5d93fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 'INCOME'), ('to_asset_source__isnull', False), ('from_asset_source__isnull', True)), models.Q(('type', 'EXPENSE'), ('from_asset_source__isnull', False), ('to_asset_source__isnull', True)), models.Q(('type', 'TRANSFER'), ('from_asset_source__isnull', False), ('to_asset_source__isnull', False)), _connector='OR'), name='transaction_from_to_by_type'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 'TRANSFER'), _negated=True), models.Q(('from_asset_source', models.F('to_asset_source')), _negated=True), _connector='OR'), name='transaction_transfer_from_ne_to'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['from_unit', 'to_unit', 'valid_at'], name='finances_ex_from_un_591ecd_idx'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.CheckConstraint(condition=models.Q(('from_unit', models.F('to_unit')), _negated=True), name='exchange_rate_from_ne_to'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('from_unit', 'to_unit', 'valid_at')},
        ),
        migrations.AddIndex(
            model_name='assetsource',
            index=models.Index(fields=['subject', 'active'], name='finances_as_subject_f1c547_idx'),
        ),
        migrations.AddIndex(
            model_name='assetsource',
            index=models.Index(fields=['unit'], name='finances_as_unit_id_e17348_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetsource',
            unique_together={('subject', 'name')},
        ),
    ]
